### ISSUE TITLE
Mitch wants a message to go along with the vote

### ISSUE THREAD

**Issue by paustint** [paustint/dongs-n-stars#6]

**Comment by bjaeger07** [comment]
Agreed. +1

**Comment by bishop6704** [comment]
I second!!

**Comment by paustint** [comment]
@bishop6704 @bjaeger07 -> This has now been implemented, you can now add messages to dongs/rockstars.  In the recent history you will see a comment icon for a hover to see the message.

Aslo, with #10, I have included a historical leaderboard that will show all the points people have been given over time.  You can hover over the number of points to get a list of all the messages that were included with those points.

You guys should test it out a bit and file any bugs if appropriate.
